---
name: build-v2
on: push
jobs:
  ci:
    name: ${{matrix.otp}} / ${{matrix.rebar3}} / ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: ["22.2"]
        os: [ubuntu-latest]
        rebar3: ['3.22.1']
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get -q update
          apt-get -y install python3
          apt-get -y install python3-pip
          pip3 install httpbin
          pip3 install gunicorn
          gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer
